
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\113\000\002\002\004\000\002\002\010\000\002\002" +
    "\010\000\002\003\005\000\002\003\005\000\002\016\002" +
    "\000\002\016\003\000\002\017\005\000\002\017\006\000" +
    "\002\017\005\000\002\021\004\000\002\021\003\000\002" +
    "\022\006\000\002\023\005\000\002\023\003\000\002\024" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\025\002\000\002\025\003\000" +
    "\002\026\004\000\002\026\004\000\002\026\003\000\002" +
    "\026\003\000\002\011\017\000\002\011\015\000\002\031" +
    "\006\000\002\031\004\000\002\012\014\000\002\012\013" +
    "\000\002\013\002\000\002\013\003\000\002\014\005\000" +
    "\002\014\003\000\002\015\004\000\002\004\004\000\002" +
    "\004\003\000\002\005\006\000\002\005\010\000\002\005" +
    "\006\000\002\005\012\000\002\005\012\000\002\005\006" +
    "\000\002\005\007\000\002\005\007\000\002\005\004\000" +
    "\002\027\002\000\002\027\003\000\002\030\005\000\002" +
    "\030\003\000\002\007\003\000\002\007\003\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\007\006" +
    "\000\002\007\005\000\002\007\005\000\002\007\005\000" +
    "\002\007\005\000\002\007\005\000\002\007\005\000\002" +
    "\007\005\000\002\007\005\000\002\007\004\000\002\007" +
    "\005\000\002\007\005\000\002\007\005\000\002\007\005" +
    "\000\002\007\005\000\002\007\005\000\002\007\005\000" +
    "\002\007\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\261\000\004\051\005\001\002\000\004\002\263\001" +
    "\002\000\004\004\006\001\002\000\004\056\007\001\002" +
    "\000\014\003\ufffc\035\ufffc\036\011\037\ufffc\040\ufffc\001" +
    "\002\000\012\003\uffed\035\uffed\037\042\040\037\001\002" +
    "\000\006\003\014\004\015\001\002\000\026\003\ufffb\004" +
    "\ufffb\030\ufffb\035\ufffb\037\ufffb\040\ufffb\041\ufffb\042\ufffb" +
    "\052\ufffb\053\ufffb\001\002\000\006\004\015\056\033\001" +
    "\002\000\004\056\032\001\002\000\006\057\ufff2\060\ufff2" +
    "\001\002\000\006\057\022\060\021\001\002\000\006\004" +
    "\ufff6\056\ufff6\001\002\000\006\057\ufff3\060\ufff3\001\002" +
    "\000\004\004\015\001\002\000\012\045\027\046\024\047" +
    "\025\050\023\001\002\000\010\004\uffee\035\uffee\056\uffee" +
    "\001\002\000\010\004\ufff0\035\ufff0\056\ufff0\001\002\000" +
    "\010\004\uffef\035\uffef\056\uffef\001\002\000\004\056\030" +
    "\001\002\000\010\004\ufff1\035\ufff1\056\ufff1\001\002\000" +
    "\006\004\ufff5\056\ufff5\001\002\000\006\057\ufff4\060\ufff4" +
    "\001\002\000\026\003\ufff8\004\ufff8\030\ufff8\035\ufff8\037" +
    "\ufff8\040\ufff8\041\ufff8\042\ufff8\052\ufff8\053\ufff8\001\002" +
    "\000\030\003\ufffa\004\ufffa\030\ufffa\035\ufffa\036\011\037" +
    "\ufffa\040\ufffa\041\ufffa\042\ufffa\052\ufffa\053\ufffa\001\002" +
    "\000\006\004\ufff7\056\ufff7\001\002\000\026\003\ufff9\004" +
    "\ufff9\030\ufff9\035\ufff9\037\ufff9\040\ufff9\041\ufff9\042\ufff9" +
    "\052\ufff9\053\ufff9\001\002\000\012\003\uffec\035\uffec\037" +
    "\042\040\037\001\002\000\004\004\242\001\002\000\012" +
    "\003\uffe8\035\uffe8\037\uffe8\040\uffe8\001\002\000\012\003" +
    "\uffe9\035\uffe9\037\uffe9\040\uffe9\001\002\000\004\004\202" +
    "\001\002\000\006\003\044\035\045\001\002\000\004\002" +
    "\uffff\001\002\000\020\003\055\004\056\030\052\041\050" +
    "\042\051\052\047\053\053\001\002\000\004\002\000\001" +
    "\002\000\004\054\176\001\002\000\020\004\071\005\070" +
    "\006\065\007\072\010\067\054\073\066\066\001\002\000" +
    "\004\004\160\001\002\000\020\004\071\005\070\006\065" +
    "\007\072\010\067\054\073\066\066\001\002\000\004\054" +
    "\147\001\002\000\022\003\uffdb\004\uffdb\030\uffdb\033\uffdb" +
    "\041\uffdb\042\uffdb\052\uffdb\053\uffdb\001\002\000\006\033" +
    "\146\056\063\001\002\000\004\021\064\001\002\000\022" +
    "\003\061\004\056\030\052\033\062\041\050\042\051\052" +
    "\047\053\053\001\002\000\022\003\uffdc\004\uffdc\030\uffdc" +
    "\033\uffdc\041\uffdc\042\uffdc\052\uffdc\053\uffdc\001\002\000" +
    "\004\056\063\001\002\000\004\002\ufffe\001\002\000\024" +
    "\003\uffd2\004\uffd2\030\uffd2\032\uffd2\033\uffd2\041\uffd2\042" +
    "\uffd2\052\uffd2\053\uffd2\001\002\000\020\004\071\005\070" +
    "\006\065\007\072\010\067\054\073\066\066\001\002\000" +
    "\054\014\uffcc\015\uffcc\016\uffcc\020\uffcc\022\uffcc\023\uffcc" +
    "\024\uffcc\025\uffcc\026\uffcc\027\uffcc\031\uffcc\034\uffcc\043" +
    "\uffcc\044\uffcc\055\uffcc\056\uffcc\060\uffcc\062\uffcc\063\uffcc" +
    "\064\uffcc\065\uffcc\001\002\000\020\004\071\005\070\006" +
    "\065\007\072\010\067\054\073\066\066\001\002\000\054" +
    "\014\uffca\015\uffca\016\uffca\020\uffca\022\uffca\023\uffca\024" +
    "\uffca\025\uffca\026\uffca\027\uffca\031\uffca\034\uffca\043\uffca" +
    "\044\uffca\055\uffca\056\uffca\060\uffca\062\uffca\063\uffca\064" +
    "\uffca\065\uffca\001\002\000\054\014\uffcd\015\uffcd\016\uffcd" +
    "\020\uffcd\022\uffcd\023\uffcd\024\uffcd\025\uffcd\026\uffcd\027" +
    "\uffcd\031\uffcd\034\uffcd\043\uffcd\044\uffcd\055\uffcd\056\uffcd" +
    "\060\uffcd\062\uffcd\063\uffcd\064\uffcd\065\uffcd\001\002\000" +
    "\056\014\uffc9\015\uffc9\016\uffc9\020\uffc9\022\uffc9\023\uffc9" +
    "\024\uffc9\025\uffc9\026\uffc9\027\uffc9\031\uffc9\034\uffc9\043" +
    "\uffc9\044\uffc9\054\136\055\uffc9\056\uffc9\060\uffc9\062\uffc9" +
    "\063\uffc9\064\uffc9\065\uffc9\001\002\000\054\014\uffcb\015" +
    "\uffcb\016\uffcb\020\uffcb\022\uffcb\023\uffcb\024\uffcb\025\uffcb" +
    "\026\uffcb\027\uffcb\031\uffcb\034\uffcb\043\uffcb\044\uffcb\055" +
    "\uffcb\056\uffcb\060\uffcb\062\uffcb\063\uffcb\064\uffcb\065\uffcb" +
    "\001\002\000\022\003\133\004\071\005\070\006\065\007" +
    "\072\010\067\054\073\066\066\001\002\000\040\014\103" +
    "\015\076\016\102\020\077\022\104\023\112\024\106\025" +
    "\105\026\100\027\111\056\110\062\107\063\101\064\113" +
    "\065\075\001\002\000\020\004\071\005\070\006\065\007" +
    "\072\010\067\054\073\066\066\001\002\000\020\004\071" +
    "\005\070\006\065\007\072\010\067\054\073\066\066\001" +
    "\002\000\020\004\071\005\070\006\065\007\072\010\067" +
    "\054\073\066\066\001\002\000\020\004\071\005\070\006" +
    "\065\007\072\010\067\054\073\066\066\001\002\000\020" +
    "\004\071\005\070\006\065\007\072\010\067\054\073\066" +
    "\066\001\002\000\020\004\071\005\070\006\065\007\072" +
    "\010\067\054\073\066\066\001\002\000\020\004\071\005" +
    "\070\006\065\007\072\010\067\054\073\066\066\001\002" +
    "\000\020\004\071\005\070\006\065\007\072\010\067\054" +
    "\073\066\066\001\002\000\020\004\071\005\070\006\065" +
    "\007\072\010\067\054\073\066\066\001\002\000\020\004" +
    "\071\005\070\006\065\007\072\010\067\054\073\066\066" +
    "\001\002\000\020\004\071\005\070\006\065\007\072\010" +
    "\067\054\073\066\066\001\002\000\024\003\uffd5\004\uffd5" +
    "\030\uffd5\032\uffd5\033\uffd5\041\uffd5\042\uffd5\052\uffd5\053" +
    "\uffd5\001\002\000\020\004\071\005\070\006\065\007\072" +
    "\010\067\054\073\066\066\001\002\000\020\004\071\005" +
    "\070\006\065\007\072\010\067\054\073\066\066\001\002" +
    "\000\020\004\071\005\070\006\065\007\072\010\067\054" +
    "\073\066\066\001\002\000\054\014\uffc0\015\uffc0\016\102" +
    "\020\077\022\uffc0\023\uffc0\024\uffc0\025\uffc0\026\uffc0\027" +
    "\uffc0\031\uffc0\034\uffc0\043\uffc0\044\uffc0\055\uffc0\056\uffc0" +
    "\060\uffc0\062\107\063\101\064\uffc0\065\075\001\002\000" +
    "\040\014\103\015\076\016\102\020\077\031\uffbd\034\uffbd" +
    "\043\uffbd\044\uffbd\055\uffbd\056\uffbd\060\uffbd\062\107\063" +
    "\101\064\113\065\075\001\002\000\040\014\103\015\076" +
    "\016\102\020\077\031\uffb9\034\uffb9\043\uffb9\044\uffb9\055" +
    "\uffb9\056\uffb9\060\uffb9\062\107\063\101\064\113\065\075" +
    "\001\002\000\054\014\uffc3\015\uffc3\016\uffc3\020\uffc3\022" +
    "\uffc3\023\uffc3\024\uffc3\025\uffc3\026\uffc3\027\uffc3\031\uffc3" +
    "\034\uffc3\043\uffc3\044\uffc3\055\uffc3\056\uffc3\060\uffc3\062" +
    "\uffc3\063\uffc3\064\uffc3\065\uffc3\001\002\000\040\014\103" +
    "\015\076\016\102\020\077\031\uffbc\034\uffbc\043\uffbc\044" +
    "\uffbc\055\uffbc\056\uffbc\060\uffbc\062\107\063\101\064\113" +
    "\065\075\001\002\000\040\014\103\015\076\016\102\020" +
    "\077\031\uffbb\034\uffbb\043\uffbb\044\uffbb\055\uffbb\056\uffbb" +
    "\060\uffbb\062\107\063\101\064\113\065\075\001\002\000" +
    "\040\014\103\015\076\016\102\020\077\031\uffbe\034\uffbe" +
    "\043\uffbe\044\uffbe\055\uffbe\056\uffbe\060\uffbe\062\107\063" +
    "\101\064\113\065\075\001\002\000\054\014\uffc7\015\uffc7" +
    "\016\102\020\077\022\uffc7\023\uffc7\024\uffc7\025\uffc7\026" +
    "\uffc7\027\uffc7\031\uffc7\034\uffc7\043\uffc7\044\uffc7\055\uffc7" +
    "\056\uffc7\060\uffc7\062\107\063\101\064\uffc7\065\075\001" +
    "\002\000\054\014\uffc5\015\uffc5\016\uffc5\020\uffc5\022\uffc5" +
    "\023\uffc5\024\uffc5\025\uffc5\026\uffc5\027\uffc5\031\uffc5\034" +
    "\uffc5\043\uffc5\044\uffc5\055\uffc5\056\uffc5\060\uffc5\062\uffc5" +
    "\063\uffc5\064\uffc5\065\uffc5\001\002\000\054\014\uffc2\015" +
    "\uffc2\016\uffc2\020\uffc2\022\uffc2\023\uffc2\024\uffc2\025\uffc2" +
    "\026\uffc2\027\uffc2\031\uffc2\034\uffc2\043\uffc2\044\uffc2\055" +
    "\uffc2\056\uffc2\060\uffc2\062\uffc2\063\uffc2\064\uffc2\065\uffc2" +
    "\001\002\000\040\014\103\015\076\016\102\020\077\031" +
    "\uffba\034\uffba\043\uffba\044\uffba\055\uffba\056\uffba\060\uffba" +
    "\062\107\063\101\064\113\065\075\001\002\000\054\014" +
    "\uffc4\015\uffc4\016\uffc4\020\uffc4\022\uffc4\023\uffc4\024\uffc4" +
    "\025\uffc4\026\uffc4\027\uffc4\031\uffc4\034\uffc4\043\uffc4\044" +
    "\uffc4\055\uffc4\056\uffc4\060\uffc4\062\uffc4\063\uffc4\064\uffc4" +
    "\065\uffc4\001\002\000\054\014\uffc6\015\uffc6\016\102\020" +
    "\077\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6\027\uffc6" +
    "\031\uffc6\034\uffc6\043\uffc6\044\uffc6\055\uffc6\056\uffc6\060" +
    "\uffc6\062\107\063\101\064\uffc6\065\075\001\002\000\054" +
    "\014\uffc1\015\uffc1\016\uffc1\020\uffc1\022\uffc1\023\uffc1\024" +
    "\uffc1\025\uffc1\026\uffc1\027\uffc1\031\uffc1\034\uffc1\043\uffc1" +
    "\044\uffc1\055\uffc1\056\uffc1\060\uffc1\062\uffc1\063\uffc1\064" +
    "\uffc1\065\uffc1\001\002\000\040\014\103\015\076\016\102" +
    "\020\077\022\104\023\112\024\106\025\105\026\100\027" +
    "\111\055\135\062\107\063\101\064\113\065\075\001\002" +
    "\000\004\055\134\001\002\000\054\014\uffb7\015\uffb7\016" +
    "\uffb7\020\uffb7\022\uffb7\023\uffb7\024\uffb7\025\uffb7\026\uffb7" +
    "\027\uffb7\031\uffb7\034\uffb7\043\uffb7\044\uffb7\055\uffb7\056" +
    "\uffb7\060\uffb7\062\uffb7\063\uffb7\064\uffb7\065\uffb7\001\002" +
    "\000\054\014\uffb8\015\uffb8\016\uffb8\020\uffb8\022\uffb8\023" +
    "\uffb8\024\uffb8\025\uffb8\026\uffb8\027\uffb8\031\uffb8\034\uffb8" +
    "\043\uffb8\044\uffb8\055\uffb8\056\uffb8\060\uffb8\062\uffb8\063" +
    "\uffb8\064\uffb8\065\uffb8\001\002\000\022\004\071\005\070" +
    "\006\065\007\072\010\067\054\073\055\uffd1\066\066\001" +
    "\002\000\006\055\uffd0\060\143\001\002\000\004\055\142" +
    "\001\002\000\042\014\103\015\076\016\102\020\077\022" +
    "\104\023\112\024\106\025\105\026\100\027\111\055\uffce" +
    "\060\uffce\062\107\063\101\064\113\065\075\001\002\000" +
    "\054\014\uffc8\015\uffc8\016\uffc8\020\uffc8\022\uffc8\023\uffc8" +
    "\024\uffc8\025\uffc8\026\uffc8\027\uffc8\031\uffc8\034\uffc8\043" +
    "\uffc8\044\uffc8\055\uffc8\056\uffc8\060\uffc8\062\uffc8\063\uffc8" +
    "\064\uffc8\065\uffc8\001\002\000\020\004\071\005\070\006" +
    "\065\007\072\010\067\054\073\066\066\001\002\000\042" +
    "\014\103\015\076\016\102\020\077\022\104\023\112\024" +
    "\106\025\105\026\100\027\111\055\uffcf\060\uffcf\062\107" +
    "\063\101\064\113\065\075\001\002\000\054\014\uffbf\015" +
    "\uffbf\016\uffbf\020\uffbf\022\uffbf\023\uffbf\024\uffbf\025\uffbf" +
    "\026\uffbf\027\uffbf\031\uffbf\034\uffbf\043\uffbf\044\uffbf\055" +
    "\uffbf\056\uffbf\060\uffbf\062\uffbf\063\uffbf\064\uffbf\065\uffbf" +
    "\001\002\000\004\002\ufffd\001\002\000\020\004\071\005" +
    "\070\006\065\007\072\010\067\054\073\066\066\001\002" +
    "\000\006\055\151\060\143\001\002\000\004\056\152\001" +
    "\002\000\024\003\uffd3\004\uffd3\030\uffd3\032\uffd3\033\uffd3" +
    "\041\uffd3\042\uffd3\052\uffd3\053\uffd3\001\002\000\040\014" +
    "\103\015\076\016\102\020\077\022\104\023\112\024\106" +
    "\025\105\026\100\027\111\031\154\062\107\063\101\064" +
    "\113\065\075\001\002\000\020\003\061\004\056\030\052" +
    "\041\050\042\051\052\047\053\053\001\002\000\024\003" +
    "\uffda\004\uffda\030\uffda\032\156\033\uffda\041\uffda\042\uffda" +
    "\052\uffda\053\uffda\001\002\000\020\003\061\004\056\030" +
    "\052\041\050\042\051\052\047\053\053\001\002\000\024" +
    "\003\uffd9\004\uffd9\030\uffd9\032\uffd9\033\uffd9\041\uffd9\042" +
    "\uffd9\052\uffd9\053\uffd9\001\002\000\004\021\161\001\002" +
    "\000\020\004\071\005\070\006\065\007\072\010\067\054" +
    "\073\066\066\001\002\000\042\014\103\015\076\016\102" +
    "\020\077\022\104\023\112\024\106\025\105\026\100\027" +
    "\111\043\163\044\164\062\107\063\101\064\113\065\075" +
    "\001\002\000\020\004\071\005\070\006\065\007\072\010" +
    "\067\054\073\066\066\001\002\000\020\004\071\005\070" +
    "\006\065\007\072\010\067\054\073\066\066\001\002\000" +
    "\040\014\103\015\076\016\102\020\077\022\104\023\112" +
    "\024\106\025\105\026\100\027\111\034\166\062\107\063" +
    "\101\064\113\065\075\001\002\000\020\003\061\004\056" +
    "\030\052\041\050\042\051\052\047\053\053\001\002\000" +
    "\024\003\uffd6\004\uffd6\030\uffd6\032\uffd6\033\uffd6\041\uffd6" +
    "\042\uffd6\052\uffd6\053\uffd6\001\002\000\040\014\103\015" +
    "\076\016\102\020\077\022\104\023\112\024\106\025\105" +
    "\026\100\027\111\034\171\062\107\063\101\064\113\065" +
    "\075\001\002\000\020\003\061\004\056\030\052\041\050" +
    "\042\051\052\047\053\053\001\002\000\024\003\uffd7\004" +
    "\uffd7\030\uffd7\032\uffd7\033\uffd7\041\uffd7\042\uffd7\052\uffd7" +
    "\053\uffd7\001\002\000\040\014\103\015\076\016\102\020" +
    "\077\022\104\023\112\024\106\025\105\026\100\027\111" +
    "\034\174\062\107\063\101\064\113\065\075\001\002\000" +
    "\020\003\061\004\056\030\052\041\050\042\051\052\047" +
    "\053\053\001\002\000\024\003\uffd8\004\uffd8\030\uffd8\032" +
    "\uffd8\033\uffd8\041\uffd8\042\uffd8\052\uffd8\053\uffd8\001\002" +
    "\000\022\004\071\005\070\006\065\007\072\010\067\054" +
    "\073\055\uffd1\066\066\001\002\000\004\055\200\001\002" +
    "\000\004\056\201\001\002\000\024\003\uffd4\004\uffd4\030" +
    "\uffd4\032\uffd4\033\uffd4\041\uffd4\042\uffd4\052\uffd4\053\uffd4" +
    "\001\002\000\004\054\203\001\002\000\016\003\206\045" +
    "\027\046\024\047\025\050\023\055\uffe1\001\002\000\004" +
    "\055\223\001\002\000\004\004\222\001\002\000\004\055" +
    "\213\001\002\000\006\055\uffde\060\uffde\001\002\000\006" +
    "\055\uffe0\060\211\001\002\000\012\045\027\046\024\047" +
    "\025\050\023\001\002\000\006\055\uffdf\060\uffdf\001\002" +
    "\000\004\057\214\001\002\000\012\045\027\046\024\047" +
    "\025\050\023\001\002\000\004\035\216\001\002\000\020" +
    "\003\061\004\056\030\052\041\050\042\051\052\047\053" +
    "\053\001\002\000\022\003\061\004\056\030\052\033\220" +
    "\041\050\042\051\052\047\053\053\001\002\000\004\056" +
    "\221\001\002\000\012\003\uffe6\035\uffe6\037\uffe6\040\uffe6" +
    "\001\002\000\006\055\uffdd\060\uffdd\001\002\000\004\057" +
    "\224\001\002\000\012\045\027\046\024\047\025\050\023" +
    "\001\002\000\004\035\226\001\002\000\022\003\ufffc\004" +
    "\ufffc\030\ufffc\036\011\041\ufffc\042\ufffc\052\ufffc\053\ufffc" +
    "\001\002\000\020\003\061\004\056\030\052\041\050\042" +
    "\051\052\047\053\053\001\002\000\020\003\231\004\232" +
    "\030\052\041\050\042\051\052\047\053\053\001\002\000" +
    "\004\056\241\001\002\000\004\021\236\001\002\000\004" +
    "\033\234\001\002\000\004\056\235\001\002\000\012\003" +
    "\uffe7\035\uffe7\037\uffe7\040\uffe7\001\002\000\020\004\071" +
    "\005\070\006\065\007\072\010\067\054\073\066\066\001" +
    "\002\000\040\014\103\015\076\016\102\020\077\022\104" +
    "\023\112\024\106\025\105\026\100\027\111\056\240\062" +
    "\107\063\101\064\113\065\075\001\002\000\022\003\uffd5" +
    "\004\uffd5\030\uffd5\033\uffe5\041\uffd5\042\uffd5\052\uffd5\053" +
    "\uffd5\001\002\000\022\003\uffd2\004\uffd2\030\uffd2\033\uffe4" +
    "\041\uffd2\042\uffd2\052\uffd2\053\uffd2\001\002\000\004\054" +
    "\243\001\002\000\016\003\245\045\027\046\024\047\025" +
    "\050\023\055\uffe1\001\002\000\004\055\253\001\002\000" +
    "\004\055\246\001\002\000\004\035\247\001\002\000\020" +
    "\003\061\004\056\030\052\041\050\042\051\052\047\053" +
    "\053\001\002\000\022\003\061\004\056\030\052\033\251" +
    "\041\050\042\051\052\047\053\053\001\002\000\004\056" +
    "\252\001\002\000\012\003\uffe2\035\uffe2\037\uffe2\040\uffe2" +
    "\001\002\000\004\035\254\001\002\000\022\003\ufffc\004" +
    "\ufffc\030\ufffc\036\011\041\ufffc\042\ufffc\052\ufffc\053\ufffc" +
    "\001\002\000\020\003\061\004\056\030\052\041\050\042" +
    "\051\052\047\053\053\001\002\000\022\003\061\004\056" +
    "\030\052\033\257\041\050\042\051\052\047\053\053\001" +
    "\002\000\004\056\260\001\002\000\012\003\uffe3\035\uffe3" +
    "\037\uffe3\040\uffe3\001\002\000\012\003\uffea\035\uffea\037" +
    "\uffea\040\uffea\001\002\000\012\003\uffeb\035\uffeb\037\uffeb" +
    "\040\uffeb\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\261\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\016\007\017\011" +
    "\001\001\000\012\011\040\012\037\025\042\026\035\001" +
    "\001\000\012\021\012\022\016\023\015\024\017\001\001" +
    "\000\002\001\001\000\010\022\033\023\015\024\017\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\030\001" +
    "\001\000\004\010\025\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\034\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\011\261\012\260\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\045\001\001\000\002\001\001\000\006\004\056" +
    "\005\053\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\172\001\001\000\002\001\001\000\004\007\152" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\073\001\001\000\002\001\001\000\004" +
    "\007\144\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\131\001\001" +
    "\000\002\001\001\000\004\007\130\001\001\000\004\007" +
    "\127\001\001\000\004\007\126\001\001\000\004\007\125" +
    "\001\001\000\004\007\124\001\001\000\004\007\123\001" +
    "\001\000\004\007\122\001\001\000\004\007\121\001\001" +
    "\000\004\007\120\001\001\000\004\007\117\001\001\000" +
    "\004\007\116\001\001\000\002\001\001\000\004\007\115" +
    "\001\001\000\004\007\114\001\001\000\004\007\113\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\007\140\027" +
    "\137\030\136\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\143\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\140\030\147\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\154\001\001\000\002\001\001\000\004\005\156\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\161" +
    "\001\001\000\002\001\001\000\004\007\167\001\001\000" +
    "\004\007\164\001\001\000\002\001\001\000\004\005\166" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\171\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\174\001\001\000\002\001\001\000\010\007\140\027" +
    "\176\030\136\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\010\204\013" +
    "\203\014\207\015\206\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\204\015\211\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\010\214\001\001\000\002\001" +
    "\001\000\006\004\216\005\053\001\001\000\004\005\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\224\001\001\000\002" +
    "\001\001\000\006\016\226\017\011\001\001\000\006\004" +
    "\227\005\053\001\001\000\006\005\057\031\232\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\236\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\010\204\013\243\014\207\015\206" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\247\005\053\001\001\000\004\005\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\016\254\017\011\001\001\000\006\004\255" +
    "\005\053\001\001\000\004\005\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private java.util.List<String> erroresSintacticos = new java.util.ArrayList<>();

    @Override
    public void syntax_error(Symbol sym) {
        String msg = String.format(
            "Error sintáctico en línea %d, columna %d: token inesperado '%s'",
            sym.left, sym.right, sym.value
        );
        erroresSintacticos.add(msg);
        System.err.println("⚠️ " + msg);
    }

    @Override
    public void unrecovered_syntax_error(Symbol sym) throws Exception {
        String msg = String.format(
            "Error grave en línea %d, columna %d: '%s'",
            sym.left, sym.right, sym.value
        );
        erroresSintacticos.add(msg);
        System.err.println("❌ " + msg);
    }

    public java.util.List<String> getErroresSintacticos() {
        return erroresSintacticos;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= PROGRAM IDENTIFIER SEMICOLON variable_sections_opt function_list_opt block 
            {
              Object RESULT =null;
		 
        System.out.println("Entrando a la producción de 'program' con 'PROGRAM IDENTIFIER SEMICOLON'");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= PROGRAM IDENTIFIER SEMICOLON variable_sections_opt function_list_opt error 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error en el bloque principal.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block ::= BEGIN statement_list END 
            {
              Object RESULT =null;
		 
        System.out.println("Entrando al bloque principal con 'BEGIN statement_list END'");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // block ::= BEGIN error END 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error dentro del bloque principal.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // variable_sections_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections_opt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // variable_sections_opt ::= variable_sections 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando variable_sections...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections_opt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable_sections ::= VAR decl_group_list SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'VAR decl_group_list SEMICOLON'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // variable_sections ::= VAR decl_group_list SEMICOLON variable_sections 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'VAR decl_group_list SEMICOLON variable_sections'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // variable_sections ::= VAR error SEMICOLON 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error en bloque VAR.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // decl_group_list ::= decl_group_list decl_group 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'decl_group_list decl_group'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_group_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // decl_group_list ::= decl_group 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'decl_group'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_group_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // decl_group ::= variable_declaration_item_list COLON type SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando declaración de variables: 'variable_declaration_item_list COLON type SEMICOLON'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_group",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // variable_declaration_item_list ::= variable_declaration_item_list COMMA variable_declaration_item 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'variable_declaration_item_list COMMA variable_declaration_item'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_declaration_item_list",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // variable_declaration_item_list ::= variable_declaration_item 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'variable_declaration_item'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_declaration_item_list",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // variable_declaration_item ::= IDENTIFIER 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando variable IDENTIFIER...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_declaration_item",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // type ::= STRING_KEYWORD 
            {
              Object RESULT =null;
		 
        System.out.println("Tipo: STRING_KEYWORD");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // type ::= INT_KEYWORD 
            {
              Object RESULT =null;
		 
        System.out.println("Tipo: INT_KEYWORD");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // type ::= REAL_KEYWORD 
            {
              Object RESULT =null;
		 
        System.out.println("Tipo: REAL_KEYWORD");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type ::= CHAR_KEYWORD 
            {
              Object RESULT =null;
		 
        System.out.println("Tipo: CHAR_KEYWORD");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // function_list_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list_opt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // function_list_opt ::= function_list 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando lista de funciones...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list_opt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // function_list ::= function_list function_declaration 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'function_declaration' en 'function_list'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // function_list ::= function_list procedure_declaration 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'procedure_declaration' en 'function_list'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // function_list ::= function_declaration 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'function_declaration'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // function_list ::= procedure_declaration 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando 'procedure_declaration'...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // function_declaration ::= FUNCTION IDENTIFIER LPAREN parameter_list_opt RPAREN COLON type BEGIN variable_sections_opt statement_list return_statement END SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Declaración de función encontrada");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_declaration",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // function_declaration ::= FUNCTION IDENTIFIER LPAREN error RPAREN COLON type BEGIN statement_list END SEMICOLON 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error en parámetros de función.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_declaration",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // return_statement ::= IDENTIFIER ASSIGN expression SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando return_statement: IDENTIFIER ASSIGN expression SEMICOLON");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_statement",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // return_statement ::= error SEMICOLON 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Falta retorno correcto en función.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_statement",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // procedure_declaration ::= PROCEDURE IDENTIFIER LPAREN parameter_list_opt RPAREN BEGIN variable_sections_opt statement_list END SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Declaración de procedimiento encontrada");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("procedure_declaration",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // procedure_declaration ::= PROCEDURE IDENTIFIER LPAREN error RPAREN BEGIN statement_list END SEMICOLON 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error en parámetros de procedimiento.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("procedure_declaration",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // parameter_list_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list_opt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parameter_list_opt ::= parameter_list 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando lista de parámetros...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list_opt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parameter_list ::= parameter_list COMMA parameter 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando parámetros separados por coma...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parameter_list ::= parameter 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando un solo parámetro...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parameter ::= type IDENTIFIER 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando parámetro de tipo IDENTIFIER...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando lista de sentencias...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // statement_list ::= statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando una sola sentencia...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // statement ::= IF expression THEN statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia IF...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // statement ::= IF expression THEN statement ELSE statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia IF con ELSE...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // statement ::= WHILE expression DO statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia WHILE...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // statement ::= FOR IDENTIFIER ASSIGN expression TO expression DO statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia FOR...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // statement ::= FOR IDENTIFIER ASSIGN expression DOWNTO expression DO statement 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia FOR con DOWNTO...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // statement ::= IDENTIFIER ASSIGN expression SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando asignación: IDENTIFIER ASSIGN expression SEMICOLON");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // statement ::= READ LPAREN arg_list_opt RPAREN SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia READ...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // statement ::= WRITE LPAREN arg_list RPAREN SEMICOLON 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando sentencia WRITE...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // statement ::= error SEMICOLON 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error general en sentencia.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // arg_list_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list_opt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // arg_list_opt ::= arg_list 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando lista de argumentos...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list_opt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // arg_list ::= arg_list COMMA expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando argumento separado por coma...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // arg_list ::= expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando un solo argumento...");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expression ::= NUMBER 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando número: NUMBER");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expression ::= REAL_NUMBER 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando número real: REAL_NUMBER");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expression ::= STRING_LITERAL 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando literal de cadena: STRING_LITERAL");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expression ::= CHAR_LITERAL 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando literal de carácter: CHAR_LITERAL");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expression ::= IDENTIFIER 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando identificador: IDENTIFIER");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expression ::= IDENTIFIER LPAREN arg_list_opt RPAREN 
            {
              Object RESULT =null;
		 
        System.out.println("Llamada a función: IDENTIFIER LPAREN arg_list_opt RPAREN");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expression ::= expression PLUS expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con '+': PLUS");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expression ::= expression MINUS expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con '-': MINUS");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expression ::= expression STAR expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con '*': STAR");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expression ::= expression SLASH expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con '/': SLASH");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expression ::= expression DIV expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'DIV': DIV");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expression ::= expression MOD expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'MOD': MOD");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expression ::= expression AND expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'AND': AND");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expression ::= expression OR expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'OR': OR");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expression ::= NOT expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'NOT': NOT");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expression ::= expression EQ expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'EQ': EQ");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expression ::= expression LT expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'LT': LT");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expression ::= expression GT expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'GT': GT");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expression ::= expression LE expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'LE': LE");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expression ::= expression GE expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'GE': GE");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expression ::= expression NE expression 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión con 'NE': NE");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expression ::= LPAREN expression RPAREN 
            {
              Object RESULT =null;
		 
        System.out.println("Procesando expresión dentro de paréntesis: LPAREN expression RPAREN");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expression ::= LPAREN error RPAREN 
            {
              Object RESULT =null;
		 
        System.err.println("⚠️ Error dentro de paréntesis.");
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
