
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\115\000\002\002\004\000\002\002\010\000\002\002" +
    "\010\000\002\003\005\000\002\003\005\000\002\016\002" +
    "\000\002\016\003\000\002\017\005\000\002\017\006\000" +
    "\002\017\005\000\002\021\004\000\002\021\003\000\002" +
    "\022\006\000\002\023\005\000\002\023\003\000\002\024" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\025\002\000\002\025\003\000" +
    "\002\026\004\000\002\026\004\000\002\026\003\000\002" +
    "\026\003\000\002\011\017\000\002\011\015\000\002\031" +
    "\006\000\002\031\004\000\002\012\014\000\002\012\013" +
    "\000\002\013\002\000\002\013\003\000\002\014\005\000" +
    "\002\014\003\000\002\015\004\000\002\004\004\000\002" +
    "\004\003\000\002\005\005\000\002\005\006\000\002\005" +
    "\010\000\002\005\006\000\002\005\012\000\002\005\012" +
    "\000\002\005\006\000\002\005\007\000\002\005\007\000" +
    "\002\005\003\000\002\005\004\000\002\027\002\000\002" +
    "\027\003\000\002\030\005\000\002\030\003\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\006\000\002\007\005\000" +
    "\002\007\005\000\002\007\005\000\002\007\005\000\002" +
    "\007\005\000\002\007\005\000\002\007\005\000\002\007" +
    "\005\000\002\007\004\000\002\007\005\000\002\007\005" +
    "\000\002\007\005\000\002\007\005\000\002\007\005\000" +
    "\002\007\005\000\002\007\005\000\002\007\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\265\000\004\051\005\001\002\000\004\002\267\001" +
    "\002\000\004\004\006\001\002\000\004\056\007\001\002" +
    "\000\014\003\ufffc\035\ufffc\036\011\037\ufffc\040\ufffc\001" +
    "\002\000\012\003\uffed\035\uffed\037\042\040\037\001\002" +
    "\000\006\003\014\004\015\001\002\000\026\003\ufffb\004" +
    "\ufffb\030\ufffb\035\ufffb\037\ufffb\040\ufffb\041\ufffb\042\ufffb" +
    "\052\ufffb\053\ufffb\001\002\000\006\004\015\056\033\001" +
    "\002\000\004\056\032\001\002\000\006\057\ufff2\060\ufff2" +
    "\001\002\000\006\057\022\060\021\001\002\000\006\004" +
    "\ufff6\056\ufff6\001\002\000\006\057\ufff3\060\ufff3\001\002" +
    "\000\004\004\015\001\002\000\012\045\027\046\024\047" +
    "\025\050\023\001\002\000\010\004\uffee\035\uffee\056\uffee" +
    "\001\002\000\010\004\ufff0\035\ufff0\056\ufff0\001\002\000" +
    "\010\004\uffef\035\uffef\056\uffef\001\002\000\004\056\030" +
    "\001\002\000\010\004\ufff1\035\ufff1\056\ufff1\001\002\000" +
    "\006\004\ufff5\056\ufff5\001\002\000\006\057\ufff4\060\ufff4" +
    "\001\002\000\026\003\ufff8\004\ufff8\030\ufff8\035\ufff8\037" +
    "\ufff8\040\ufff8\041\ufff8\042\ufff8\052\ufff8\053\ufff8\001\002" +
    "\000\030\003\ufffa\004\ufffa\030\ufffa\035\ufffa\036\011\037" +
    "\ufffa\040\ufffa\041\ufffa\042\ufffa\052\ufffa\053\ufffa\001\002" +
    "\000\006\004\ufff7\056\ufff7\001\002\000\026\003\ufff9\004" +
    "\ufff9\030\ufff9\035\ufff9\037\ufff9\040\ufff9\041\ufff9\042\ufff9" +
    "\052\ufff9\053\ufff9\001\002\000\012\003\uffec\035\uffec\037" +
    "\042\040\037\001\002\000\004\004\246\001\002\000\012" +
    "\003\uffe8\035\uffe8\037\uffe8\040\uffe8\001\002\000\012\003" +
    "\uffe9\035\uffe9\037\uffe9\040\uffe9\001\002\000\004\004\206" +
    "\001\002\000\006\003\044\035\045\001\002\000\004\002" +
    "\uffff\001\002\000\022\003\056\004\057\030\053\035\061" +
    "\041\050\042\051\052\047\053\055\001\002\000\004\002" +
    "\000\001\002\000\004\054\202\001\002\000\020\004\075" +
    "\005\074\006\071\007\076\010\073\054\077\066\072\001" +
    "\002\000\004\004\164\001\002\000\026\003\uffd1\004\uffd1" +
    "\030\uffd1\032\uffd1\033\uffd1\035\uffd1\041\uffd1\042\uffd1\052" +
    "\uffd1\053\uffd1\001\002\000\020\004\075\005\074\006\071" +
    "\007\076\010\073\054\077\066\072\001\002\000\024\003" +
    "\uffdb\004\uffdb\030\uffdb\033\uffdb\035\uffdb\041\uffdb\042\uffdb" +
    "\052\uffdb\053\uffdb\001\002\000\004\054\153\001\002\000" +
    "\006\033\152\056\066\001\002\000\004\021\070\001\002" +
    "\000\024\003\062\004\057\030\053\033\067\035\061\041" +
    "\050\042\051\052\047\053\055\001\002\000\022\003\062" +
    "\004\057\030\053\035\061\041\050\042\051\052\047\053" +
    "\055\001\002\000\004\056\066\001\002\000\024\003\062" +
    "\004\057\030\053\033\065\035\061\041\050\042\051\052" +
    "\047\053\055\001\002\000\024\003\uffdc\004\uffdc\030\uffdc" +
    "\033\uffdc\035\uffdc\041\uffdc\042\uffdc\052\uffdc\053\uffdc\001" +
    "\002\000\026\003\uffda\004\uffda\030\uffda\032\uffda\033\uffda" +
    "\035\uffda\041\uffda\042\uffda\052\uffda\053\uffda\001\002\000" +
    "\026\003\uffd0\004\uffd0\030\uffd0\032\uffd0\033\uffd0\035\uffd0" +
    "\041\uffd0\042\uffd0\052\uffd0\053\uffd0\001\002\000\004\002" +
    "\ufffe\001\002\000\020\004\075\005\074\006\071\007\076" +
    "\010\073\054\077\066\072\001\002\000\054\014\uffca\015" +
    "\uffca\016\uffca\020\uffca\022\uffca\023\uffca\024\uffca\025\uffca" +
    "\026\uffca\027\uffca\031\uffca\034\uffca\043\uffca\044\uffca\055" +
    "\uffca\056\uffca\060\uffca\062\uffca\063\uffca\064\uffca\065\uffca" +
    "\001\002\000\020\004\075\005\074\006\071\007\076\010" +
    "\073\054\077\066\072\001\002\000\054\014\uffc8\015\uffc8" +
    "\016\uffc8\020\uffc8\022\uffc8\023\uffc8\024\uffc8\025\uffc8\026" +
    "\uffc8\027\uffc8\031\uffc8\034\uffc8\043\uffc8\044\uffc8\055\uffc8" +
    "\056\uffc8\060\uffc8\062\uffc8\063\uffc8\064\uffc8\065\uffc8\001" +
    "\002\000\054\014\uffcb\015\uffcb\016\uffcb\020\uffcb\022\uffcb" +
    "\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\031\uffcb\034" +
    "\uffcb\043\uffcb\044\uffcb\055\uffcb\056\uffcb\060\uffcb\062\uffcb" +
    "\063\uffcb\064\uffcb\065\uffcb\001\002\000\056\014\uffc7\015" +
    "\uffc7\016\uffc7\020\uffc7\022\uffc7\023\uffc7\024\uffc7\025\uffc7" +
    "\026\uffc7\027\uffc7\031\uffc7\034\uffc7\043\uffc7\044\uffc7\054" +
    "\142\055\uffc7\056\uffc7\060\uffc7\062\uffc7\063\uffc7\064\uffc7" +
    "\065\uffc7\001\002\000\054\014\uffc9\015\uffc9\016\uffc9\020" +
    "\uffc9\022\uffc9\023\uffc9\024\uffc9\025\uffc9\026\uffc9\027\uffc9" +
    "\031\uffc9\034\uffc9\043\uffc9\044\uffc9\055\uffc9\056\uffc9\060" +
    "\uffc9\062\uffc9\063\uffc9\064\uffc9\065\uffc9\001\002\000\022" +
    "\003\137\004\075\005\074\006\071\007\076\010\073\054" +
    "\077\066\072\001\002\000\040\014\110\015\102\016\106" +
    "\020\103\022\107\023\116\024\113\025\111\026\104\027" +
    "\115\056\114\062\112\063\105\064\117\065\101\001\002" +
    "\000\020\004\075\005\074\006\071\007\076\010\073\054" +
    "\077\066\072\001\002\000\020\004\075\005\074\006\071" +
    "\007\076\010\073\054\077\066\072\001\002\000\020\004" +
    "\075\005\074\006\071\007\076\010\073\054\077\066\072" +
    "\001\002\000\020\004\075\005\074\006\071\007\076\010" +
    "\073\054\077\066\072\001\002\000\020\004\075\005\074" +
    "\006\071\007\076\010\073\054\077\066\072\001\002\000" +
    "\020\004\075\005\074\006\071\007\076\010\073\054\077" +
    "\066\072\001\002\000\020\004\075\005\074\006\071\007" +
    "\076\010\073\054\077\066\072\001\002\000\020\004\075" +
    "\005\074\006\071\007\076\010\073\054\077\066\072\001" +
    "\002\000\020\004\075\005\074\006\071\007\076\010\073" +
    "\054\077\066\072\001\002\000\020\004\075\005\074\006" +
    "\071\007\076\010\073\054\077\066\072\001\002\000\020" +
    "\004\075\005\074\006\071\007\076\010\073\054\077\066" +
    "\072\001\002\000\026\003\uffd4\004\uffd4\030\uffd4\032\uffd4" +
    "\033\uffd4\035\uffd4\041\uffd4\042\uffd4\052\uffd4\053\uffd4\001" +
    "\002\000\020\004\075\005\074\006\071\007\076\010\073" +
    "\054\077\066\072\001\002\000\020\004\075\005\074\006" +
    "\071\007\076\010\073\054\077\066\072\001\002\000\020" +
    "\004\075\005\074\006\071\007\076\010\073\054\077\066" +
    "\072\001\002\000\054\014\uffbe\015\uffbe\016\106\020\103" +
    "\022\uffbe\023\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\031" +
    "\uffbe\034\uffbe\043\uffbe\044\uffbe\055\uffbe\056\uffbe\060\uffbe" +
    "\062\112\063\105\064\uffbe\065\101\001\002\000\040\014" +
    "\110\015\102\016\106\020\103\031\uffbb\034\uffbb\043\uffbb" +
    "\044\uffbb\055\uffbb\056\uffbb\060\uffbb\062\112\063\105\064" +
    "\117\065\101\001\002\000\040\014\110\015\102\016\106" +
    "\020\103\031\uffb7\034\uffb7\043\uffb7\044\uffb7\055\uffb7\056" +
    "\uffb7\060\uffb7\062\112\063\105\064\117\065\101\001\002" +
    "\000\040\014\110\015\102\016\106\020\103\031\uffba\034" +
    "\uffba\043\uffba\044\uffba\055\uffba\056\uffba\060\uffba\062\112" +
    "\063\105\064\117\065\101\001\002\000\054\014\uffc1\015" +
    "\uffc1\016\uffc1\020\uffc1\022\uffc1\023\uffc1\024\uffc1\025\uffc1" +
    "\026\uffc1\027\uffc1\031\uffc1\034\uffc1\043\uffc1\044\uffc1\055" +
    "\uffc1\056\uffc1\060\uffc1\062\uffc1\063\uffc1\064\uffc1\065\uffc1" +
    "\001\002\000\040\014\110\015\102\016\106\020\103\031" +
    "\uffb9\034\uffb9\043\uffb9\044\uffb9\055\uffb9\056\uffb9\060\uffb9" +
    "\062\112\063\105\064\117\065\101\001\002\000\054\014" +
    "\uffc5\015\uffc5\016\106\020\103\022\uffc5\023\uffc5\024\uffc5" +
    "\025\uffc5\026\uffc5\027\uffc5\031\uffc5\034\uffc5\043\uffc5\044" +
    "\uffc5\055\uffc5\056\uffc5\060\uffc5\062\112\063\105\064\uffc5" +
    "\065\101\001\002\000\040\014\110\015\102\016\106\020" +
    "\103\031\uffbc\034\uffbc\043\uffbc\044\uffbc\055\uffbc\056\uffbc" +
    "\060\uffbc\062\112\063\105\064\117\065\101\001\002\000" +
    "\054\014\uffc3\015\uffc3\016\uffc3\020\uffc3\022\uffc3\023\uffc3" +
    "\024\uffc3\025\uffc3\026\uffc3\027\uffc3\031\uffc3\034\uffc3\043" +
    "\uffc3\044\uffc3\055\uffc3\056\uffc3\060\uffc3\062\uffc3\063\uffc3" +
    "\064\uffc3\065\uffc3\001\002\000\054\014\uffc0\015\uffc0\016" +
    "\uffc0\020\uffc0\022\uffc0\023\uffc0\024\uffc0\025\uffc0\026\uffc0" +
    "\027\uffc0\031\uffc0\034\uffc0\043\uffc0\044\uffc0\055\uffc0\056" +
    "\uffc0\060\uffc0\062\uffc0\063\uffc0\064\uffc0\065\uffc0\001\002" +
    "\000\040\014\110\015\102\016\106\020\103\031\uffb8\034" +
    "\uffb8\043\uffb8\044\uffb8\055\uffb8\056\uffb8\060\uffb8\062\112" +
    "\063\105\064\117\065\101\001\002\000\054\014\uffc2\015" +
    "\uffc2\016\uffc2\020\uffc2\022\uffc2\023\uffc2\024\uffc2\025\uffc2" +
    "\026\uffc2\027\uffc2\031\uffc2\034\uffc2\043\uffc2\044\uffc2\055" +
    "\uffc2\056\uffc2\060\uffc2\062\uffc2\063\uffc2\064\uffc2\065\uffc2" +
    "\001\002\000\054\014\uffc4\015\uffc4\016\106\020\103\022" +
    "\uffc4\023\uffc4\024\uffc4\025\uffc4\026\uffc4\027\uffc4\031\uffc4" +
    "\034\uffc4\043\uffc4\044\uffc4\055\uffc4\056\uffc4\060\uffc4\062" +
    "\112\063\105\064\uffc4\065\101\001\002\000\054\014\uffbf" +
    "\015\uffbf\016\uffbf\020\uffbf\022\uffbf\023\uffbf\024\uffbf\025" +
    "\uffbf\026\uffbf\027\uffbf\031\uffbf\034\uffbf\043\uffbf\044\uffbf" +
    "\055\uffbf\056\uffbf\060\uffbf\062\uffbf\063\uffbf\064\uffbf\065" +
    "\uffbf\001\002\000\040\014\110\015\102\016\106\020\103" +
    "\022\107\023\116\024\113\025\111\026\104\027\115\055" +
    "\141\062\112\063\105\064\117\065\101\001\002\000\004" +
    "\055\140\001\002\000\054\014\uffb5\015\uffb5\016\uffb5\020" +
    "\uffb5\022\uffb5\023\uffb5\024\uffb5\025\uffb5\026\uffb5\027\uffb5" +
    "\031\uffb5\034\uffb5\043\uffb5\044\uffb5\055\uffb5\056\uffb5\060" +
    "\uffb5\062\uffb5\063\uffb5\064\uffb5\065\uffb5\001\002\000\054" +
    "\014\uffb6\015\uffb6\016\uffb6\020\uffb6\022\uffb6\023\uffb6\024" +
    "\uffb6\025\uffb6\026\uffb6\027\uffb6\031\uffb6\034\uffb6\043\uffb6" +
    "\044\uffb6\055\uffb6\056\uffb6\060\uffb6\062\uffb6\063\uffb6\064" +
    "\uffb6\065\uffb6\001\002\000\022\004\075\005\074\006\071" +
    "\007\076\010\073\054\077\055\uffcf\066\072\001\002\000" +
    "\006\055\uffce\060\147\001\002\000\004\055\146\001\002" +
    "\000\042\014\110\015\102\016\106\020\103\022\107\023" +
    "\116\024\113\025\111\026\104\027\115\055\uffcc\060\uffcc" +
    "\062\112\063\105\064\117\065\101\001\002\000\054\014" +
    "\uffc6\015\uffc6\016\uffc6\020\uffc6\022\uffc6\023\uffc6\024\uffc6" +
    "\025\uffc6\026\uffc6\027\uffc6\031\uffc6\034\uffc6\043\uffc6\044" +
    "\uffc6\055\uffc6\056\uffc6\060\uffc6\062\uffc6\063\uffc6\064\uffc6" +
    "\065\uffc6\001\002\000\020\004\075\005\074\006\071\007" +
    "\076\010\073\054\077\066\072\001\002\000\042\014\110" +
    "\015\102\016\106\020\103\022\107\023\116\024\113\025" +
    "\111\026\104\027\115\055\uffcd\060\uffcd\062\112\063\105" +
    "\064\117\065\101\001\002\000\054\014\uffbd\015\uffbd\016" +
    "\uffbd\020\uffbd\022\uffbd\023\uffbd\024\uffbd\025\uffbd\026\uffbd" +
    "\027\uffbd\031\uffbd\034\uffbd\043\uffbd\044\uffbd\055\uffbd\056" +
    "\uffbd\060\uffbd\062\uffbd\063\uffbd\064\uffbd\065\uffbd\001\002" +
    "\000\004\002\ufffd\001\002\000\020\004\075\005\074\006" +
    "\071\007\076\010\073\054\077\066\072\001\002\000\006" +
    "\055\155\060\147\001\002\000\004\056\156\001\002\000" +
    "\026\003\uffd2\004\uffd2\030\uffd2\032\uffd2\033\uffd2\035\uffd2" +
    "\041\uffd2\042\uffd2\052\uffd2\053\uffd2\001\002\000\040\014" +
    "\110\015\102\016\106\020\103\022\107\023\116\024\113" +
    "\025\111\026\104\027\115\031\160\062\112\063\105\064" +
    "\117\065\101\001\002\000\022\003\062\004\057\030\053" +
    "\035\061\041\050\042\051\052\047\053\055\001\002\000" +
    "\026\003\uffd9\004\uffd9\030\uffd9\032\162\033\uffd9\035\uffd9" +
    "\041\uffd9\042\uffd9\052\uffd9\053\uffd9\001\002\000\022\003" +
    "\062\004\057\030\053\035\061\041\050\042\051\052\047" +
    "\053\055\001\002\000\026\003\uffd8\004\uffd8\030\uffd8\032" +
    "\uffd8\033\uffd8\035\uffd8\041\uffd8\042\uffd8\052\uffd8\053\uffd8" +
    "\001\002\000\004\021\165\001\002\000\020\004\075\005" +
    "\074\006\071\007\076\010\073\054\077\066\072\001\002" +
    "\000\042\014\110\015\102\016\106\020\103\022\107\023" +
    "\116\024\113\025\111\026\104\027\115\043\167\044\170" +
    "\062\112\063\105\064\117\065\101\001\002\000\020\004" +
    "\075\005\074\006\071\007\076\010\073\054\077\066\072" +
    "\001\002\000\020\004\075\005\074\006\071\007\076\010" +
    "\073\054\077\066\072\001\002\000\040\014\110\015\102" +
    "\016\106\020\103\022\107\023\116\024\113\025\111\026" +
    "\104\027\115\034\172\062\112\063\105\064\117\065\101" +
    "\001\002\000\022\003\062\004\057\030\053\035\061\041" +
    "\050\042\051\052\047\053\055\001\002\000\026\003\uffd5" +
    "\004\uffd5\030\uffd5\032\uffd5\033\uffd5\035\uffd5\041\uffd5\042" +
    "\uffd5\052\uffd5\053\uffd5\001\002\000\040\014\110\015\102" +
    "\016\106\020\103\022\107\023\116\024\113\025\111\026" +
    "\104\027\115\034\175\062\112\063\105\064\117\065\101" +
    "\001\002\000\022\003\062\004\057\030\053\035\061\041" +
    "\050\042\051\052\047\053\055\001\002\000\026\003\uffd6" +
    "\004\uffd6\030\uffd6\032\uffd6\033\uffd6\035\uffd6\041\uffd6\042" +
    "\uffd6\052\uffd6\053\uffd6\001\002\000\040\014\110\015\102" +
    "\016\106\020\103\022\107\023\116\024\113\025\111\026" +
    "\104\027\115\034\200\062\112\063\105\064\117\065\101" +
    "\001\002\000\022\003\062\004\057\030\053\035\061\041" +
    "\050\042\051\052\047\053\055\001\002\000\026\003\uffd7" +
    "\004\uffd7\030\uffd7\032\uffd7\033\uffd7\035\uffd7\041\uffd7\042" +
    "\uffd7\052\uffd7\053\uffd7\001\002\000\022\004\075\005\074" +
    "\006\071\007\076\010\073\054\077\055\uffcf\066\072\001" +
    "\002\000\004\055\204\001\002\000\004\056\205\001\002" +
    "\000\026\003\uffd3\004\uffd3\030\uffd3\032\uffd3\033\uffd3\035" +
    "\uffd3\041\uffd3\042\uffd3\052\uffd3\053\uffd3\001\002\000\004" +
    "\054\207\001\002\000\016\003\212\045\027\046\024\047" +
    "\025\050\023\055\uffe1\001\002\000\004\055\227\001\002" +
    "\000\004\004\226\001\002\000\004\055\217\001\002\000" +
    "\006\055\uffde\060\uffde\001\002\000\006\055\uffe0\060\215" +
    "\001\002\000\012\045\027\046\024\047\025\050\023\001" +
    "\002\000\006\055\uffdf\060\uffdf\001\002\000\004\057\220" +
    "\001\002\000\012\045\027\046\024\047\025\050\023\001" +
    "\002\000\004\035\222\001\002\000\022\003\062\004\057" +
    "\030\053\035\061\041\050\042\051\052\047\053\055\001" +
    "\002\000\024\003\062\004\057\030\053\033\224\035\061" +
    "\041\050\042\051\052\047\053\055\001\002\000\004\056" +
    "\225\001\002\000\012\003\uffe6\035\uffe6\037\uffe6\040\uffe6" +
    "\001\002\000\006\055\uffdd\060\uffdd\001\002\000\004\057" +
    "\230\001\002\000\012\045\027\046\024\047\025\050\023" +
    "\001\002\000\004\035\232\001\002\000\024\003\ufffc\004" +
    "\ufffc\030\ufffc\035\ufffc\036\011\041\ufffc\042\ufffc\052\ufffc" +
    "\053\ufffc\001\002\000\022\003\062\004\057\030\053\035" +
    "\061\041\050\042\051\052\047\053\055\001\002\000\022" +
    "\003\235\004\236\030\053\035\061\041\050\042\051\052" +
    "\047\053\055\001\002\000\004\056\245\001\002\000\004" +
    "\021\242\001\002\000\004\033\240\001\002\000\004\056" +
    "\241\001\002\000\012\003\uffe7\035\uffe7\037\uffe7\040\uffe7" +
    "\001\002\000\020\004\075\005\074\006\071\007\076\010" +
    "\073\054\077\066\072\001\002\000\040\014\110\015\102" +
    "\016\106\020\103\022\107\023\116\024\113\025\111\026" +
    "\104\027\115\056\244\062\112\063\105\064\117\065\101" +
    "\001\002\000\024\003\uffd4\004\uffd4\030\uffd4\033\uffe5\035" +
    "\uffd4\041\uffd4\042\uffd4\052\uffd4\053\uffd4\001\002\000\024" +
    "\003\uffd0\004\uffd0\030\uffd0\033\uffe4\035\uffd0\041\uffd0\042" +
    "\uffd0\052\uffd0\053\uffd0\001\002\000\004\054\247\001\002" +
    "\000\016\003\251\045\027\046\024\047\025\050\023\055" +
    "\uffe1\001\002\000\004\055\257\001\002\000\004\055\252" +
    "\001\002\000\004\035\253\001\002\000\022\003\062\004" +
    "\057\030\053\035\061\041\050\042\051\052\047\053\055" +
    "\001\002\000\024\003\062\004\057\030\053\033\255\035" +
    "\061\041\050\042\051\052\047\053\055\001\002\000\004" +
    "\056\256\001\002\000\012\003\uffe2\035\uffe2\037\uffe2\040" +
    "\uffe2\001\002\000\004\035\260\001\002\000\024\003\ufffc" +
    "\004\ufffc\030\ufffc\035\ufffc\036\011\041\ufffc\042\ufffc\052" +
    "\ufffc\053\ufffc\001\002\000\022\003\062\004\057\030\053" +
    "\035\061\041\050\042\051\052\047\053\055\001\002\000" +
    "\024\003\062\004\057\030\053\033\263\035\061\041\050" +
    "\042\051\052\047\053\055\001\002\000\004\056\264\001" +
    "\002\000\012\003\uffe3\035\uffe3\037\uffe3\040\uffe3\001\002" +
    "\000\012\003\uffea\035\uffea\037\uffea\040\uffea\001\002\000" +
    "\012\003\uffeb\035\uffeb\037\uffeb\040\uffeb\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\265\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\016\007\017\011" +
    "\001\001\000\012\011\040\012\037\025\042\026\035\001" +
    "\001\000\012\021\012\022\016\023\015\024\017\001\001" +
    "\000\002\001\001\000\010\022\033\023\015\024\017\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\030\001" +
    "\001\000\004\010\025\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\034\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\011\265\012\264\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\045\001\001\000\002\001\001\000\010\004\057" +
    "\005\053\020\051\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\176\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\156\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\063\020\051\001\001\000\010\004\062\005\053\020" +
    "\051\001\001\000\002\001\001\000\006\005\063\020\051" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\077\001\001\000\002" +
    "\001\001\000\004\007\150\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\135\001\001\000\002\001\001\000\004\007\134\001" +
    "\001\000\004\007\133\001\001\000\004\007\132\001\001" +
    "\000\004\007\131\001\001\000\004\007\130\001\001\000" +
    "\004\007\127\001\001\000\004\007\126\001\001\000\004" +
    "\007\125\001\001\000\004\007\124\001\001\000\004\007" +
    "\123\001\001\000\004\007\122\001\001\000\002\001\001" +
    "\000\004\007\121\001\001\000\004\007\120\001\001\000" +
    "\004\007\117\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\144\027\143\030\142\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\147\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\007\144\030\153\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\005\160\020\051\001\001\000\002\001" +
    "\001\000\006\005\162\020\051\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\165\001\001\000\002\001" +
    "\001\000\004\007\173\001\001\000\004\007\170\001\001" +
    "\000\002\001\001\000\006\005\172\020\051\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\005\175\020\051" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\200\020\051\001\001\000\002\001\001\000\010\007\144" +
    "\027\202\030\142\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\010\210" +
    "\013\207\014\213\015\212\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\010\210\015\215\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\220\001\001\000\002" +
    "\001\001\000\010\004\222\005\053\020\051\001\001\000" +
    "\006\005\063\020\051\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\230\001\001\000\002\001\001\000\006\016\232\017\011" +
    "\001\001\000\010\004\233\005\053\020\051\001\001\000" +
    "\010\005\063\020\051\031\236\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\007\242\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\010\210\013\247\014\213\015\212\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\004" +
    "\253\005\053\020\051\001\001\000\006\005\063\020\051" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\016\260\017\011\001\001\000\010\004\261" +
    "\005\053\020\051\001\001\000\006\005\063\020\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private java.util.List<String> erroresSintacticos = new java.util.ArrayList<>();

    @Override
    public void syntax_error(Symbol sym) {
        String msg = String.format(
            "Error sintáctico en línea %d, columna %d: token inesperado '%s'",
            sym.left, sym.right, sym.value
        );
        erroresSintacticos.add(msg);
        System.err.println("⚠️ " + msg);
    }

    @Override
    public void unrecovered_syntax_error(Symbol sym) throws Exception {
        String msg = String.format(
            "Error grave en línea %d, columna %d: '%s'",
            sym.left, sym.right, sym.value
        );
        erroresSintacticos.add(msg);
        System.err.println("❌ " + msg);
    }

    public java.util.List<String> getErroresSintacticos() {
        return erroresSintacticos;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= PROGRAM IDENTIFIER SEMICOLON variable_sections_opt function_list_opt block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= PROGRAM IDENTIFIER SEMICOLON variable_sections_opt function_list_opt error 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error en el bloque principal."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block ::= BEGIN statement_list END 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // block ::= BEGIN error END 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error dentro del bloque principal."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // variable_sections_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections_opt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // variable_sections_opt ::= variable_sections 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections_opt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable_sections ::= VAR decl_group_list SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // variable_sections ::= VAR decl_group_list SEMICOLON variable_sections 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // variable_sections ::= VAR error SEMICOLON 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error en bloque VAR."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_sections",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // decl_group_list ::= decl_group_list decl_group 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_group_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // decl_group_list ::= decl_group 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_group_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // decl_group ::= variable_declaration_item_list COLON type SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_group",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // variable_declaration_item_list ::= variable_declaration_item_list COMMA variable_declaration_item 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_declaration_item_list",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // variable_declaration_item_list ::= variable_declaration_item 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_declaration_item_list",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // variable_declaration_item ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable_declaration_item",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // type ::= STRING_KEYWORD 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // type ::= INT_KEYWORD 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // type ::= REAL_KEYWORD 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type ::= CHAR_KEYWORD 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // function_list_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list_opt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // function_list_opt ::= function_list 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list_opt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // function_list ::= function_list function_declaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // function_list ::= function_list procedure_declaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // function_list ::= function_declaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // function_list ::= procedure_declaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // function_declaration ::= FUNCTION IDENTIFIER LPAREN parameter_list_opt RPAREN COLON type BEGIN variable_sections_opt statement_list return_statement END SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_declaration",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // function_declaration ::= FUNCTION IDENTIFIER LPAREN error RPAREN COLON type BEGIN statement_list END SEMICOLON 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error en parámetros de función."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_declaration",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // return_statement ::= IDENTIFIER ASSIGN expression SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println("📤 Retorno de función detectado correctamente."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_statement",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // return_statement ::= error SEMICOLON 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Falta retorno correcto en función."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_statement",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // procedure_declaration ::= PROCEDURE IDENTIFIER LPAREN parameter_list_opt RPAREN BEGIN variable_sections_opt statement_list END SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("procedure_declaration",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // procedure_declaration ::= PROCEDURE IDENTIFIER LPAREN error RPAREN BEGIN statement_list END SEMICOLON 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error en parámetros de procedimiento."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("procedure_declaration",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // parameter_list_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list_opt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parameter_list_opt ::= parameter_list 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list_opt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parameter_list ::= parameter_list COMMA parameter 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parameter_list ::= parameter 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter_list",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parameter ::= type IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parameter",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // statement_list ::= statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // statement ::= BEGIN statement_list END 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // statement ::= IF expression THEN statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // statement ::= IF expression THEN statement ELSE statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // statement ::= WHILE expression DO statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // statement ::= FOR IDENTIFIER ASSIGN expression TO expression DO statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // statement ::= FOR IDENTIFIER ASSIGN expression DOWNTO expression DO statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // statement ::= IDENTIFIER ASSIGN expression SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // statement ::= READ LPAREN arg_list_opt RPAREN SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // statement ::= WRITE LPAREN arg_list RPAREN SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // statement ::= variable_section 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // statement ::= error SEMICOLON 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error general en sentencia."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // arg_list_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list_opt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // arg_list_opt ::= arg_list 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list_opt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // arg_list ::= arg_list COMMA expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // arg_list ::= expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expression ::= NUMBER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expression ::= REAL_NUMBER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expression ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expression ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expression ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expression ::= IDENTIFIER LPAREN arg_list_opt RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expression ::= expression PLUS expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expression ::= expression MINUS expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expression ::= expression STAR expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expression ::= expression SLASH expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expression ::= expression DIV expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expression ::= expression MOD expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expression ::= expression AND expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expression ::= expression OR expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expression ::= NOT expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expression ::= expression EQ expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expression ::= expression LT expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expression ::= expression GT expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expression ::= expression LE expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expression ::= expression GE expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expression ::= expression NE expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expression ::= LPAREN expression RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expression ::= LPAREN error RPAREN 
            {
              Object RESULT =null;
		 System.err.println("⚠️ Error dentro de paréntesis."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
