
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int STRING_LITERAL = 4;
  public static final int FUNCTION = 23;
  public static final int POWER = 15;
  public static final int GE = 13;
  public static final int SLASH = 8;
  public static final int REAL_KEYWORD = 30;
  public static final int LPAREN = 32;
  public static final int FOR = 26;
  public static final int MINUS = 6;
  public static final int STAR = 7;
  public static final int RPAREN = 33;
  public static final int SEMICOLON = 34;
  public static final int LT = 10;
  public static final int COMMA = 36;
  public static final int BEGIN = 21;
  public static final int PLUS = 5;
  public static final int ASSIGN = 9;
  public static final int IF = 16;
  public static final int LE = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NUMBER = 3;
  public static final int COLON = 35;
  public static final int ELSE = 18;
  public static final int TO = 27;
  public static final int WHILE = 25;
  public static final int THEN = 17;
  public static final int NE = 14;
  public static final int END = 19;
  public static final int INT_KEYWORD = 29;
  public static final int STRING_KEYWORD = 28;
  public static final int CHAR_KEYWORD = 31;
  public static final int GT = 11;
  public static final int VAR = 22;
  public static final int PROCEDURE = 24;
  public static final int DO = 20;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "NUMBER",
  "STRING_LITERAL",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "ASSIGN",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "POWER",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "DO",
  "BEGIN",
  "VAR",
  "FUNCTION",
  "PROCEDURE",
  "WHILE",
  "FOR",
  "TO",
  "STRING_KEYWORD",
  "INT_KEYWORD",
  "REAL_KEYWORD",
  "CHAR_KEYWORD",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COLON",
  "COMMA"
  };
}

